name = "Tech Progression"
author = "west3436"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aad05a0e0f9e00e5f77464ad4b7a6ab31f3b9dac887827c00e52b1864b3ff062"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
