name = "Tech Progression"
author = "west3436"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3edf650e3641d10c09d1b521da00b2760aac7e3adcec22ec5cf4ae5a6fda4f4e"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
