name = "Tech Progression"
author = "west3436"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7833a0c84f07714e8d5393c33f6cf583a6246e95d8ac5499002a082cc19daa7e"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
