name = "Tech Progression"
author = "west3436"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09ea12699eca7abc977639c620d8b9b096c77102511234f24fb1ed53fdfb5514"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
