name = "Tech Progression"
author = "west3436"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4975363ab1fde90850836660e99204e43f95b593a3f9a6d5db889c0625fab12c"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
